# Generated by Django 3.2.7 on 2021-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210921_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
